language: android

android:
  components:
    - build-tools-21.1.2
    - android-20

sudo: false

addons:
  apt_packages:
    - gcc
    - g++
    - gcc-multilib
    - g++-multilib
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-i686
    - g++-mingw-w64-i686
    - gfortran-mingw-w64-i686
    - gcc-mingw32
    - mingw-w64
    - lib32z1

install:
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin -O ndk.bin; fi
  - chmod a+x ndk.bin
  - ./ndk.bin -y | grep -v Extracting

jdk: oraclejdk7

script:
  - ant -f build-linux32.xml -Dhas-compiler=true
  - ant -f build-linux64.xml -Dhas-compiler=true
  - ant -f build-windows32.xml -Dhas-compiler=true
  - ant -f build-windows64.xml -Dhas-compiler=true